<?php

namespace Database\Seeders;

use App\Models\SIK\SikBiodata;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

function stripNonNumeric($input)
{
    // Use preg_replace to remove all characters that are not digits (0-9)
    $output = preg_replace('/\D/', '', $input);
    return $output;
}

class SikBiodataUpdateNidnOther extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        //
        $jsonArr = [
            [
                "nidn" => "0718059602",
                "nik" => "19960518260320248",
                "nama" => "ACHMAD MUFLIQ",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "0727018004",
                "nik" => "19800127011114207",
                "nama" => "ACHMAD WAHYUDI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0702018901",
                "nik" => "19890102170222405",
                "nama" => "ACHMAD WICAKSONO",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0709029202",
                "nik" => "19920209170222400",
                "nama" => "ACHMAD ZAKI",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0715099801",
                "nik" => "19980917030321252",
                "nama" => "AFIFATUS SHOLIKHAH",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "6",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0715087303",
                "nik" => "19730815030815346",
                "nama" => "AGUS RACHMAD PURNAMA",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0718047706",
                "nik" => "19770418011018235",
                "nama" => "ALI MASYKURI",
                "Penempatan" => "S1 - Pendidikan Islam Anak Usia Dini",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "12",
                "fakultas_id" => "5",
                "status" => "3",
            ],
            [
                "nidn" => "0719019603",
                "nik" => "19960119240523421",
                "nama" => "AMALIA HARTININGRUM",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0726127201",
                "nik" => "19721226251014318",
                "nama" => "ANA CHRISTANTI",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0728099202",
                "nik" => "19920928011117378",
                "nama" => "ANGGA LISDIYANTO",
                "Penempatan" => "S1 - Teknik Informatika",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "3",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0708059404",
                "nik" => "19940508250822409",
                "nama" => "ANGGAY LURI PRAMANA",
                "Penempatan" => "S1 - Teknik Informatika",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "3",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0706119202",
                "nik" => "19921106010419386",
                "nama" => "ARDA SURYA EDITYA",
                "Penempatan" => "S1 - Teknik Informatika",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "3",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0703048903",
                "nik" => "19890403050115314",
                "nama" => "ARDHANA RAHMAYANTI",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0725117801",
                "nik" => "19781123030117368",
                "nama" => "ARIEF SAPUTRO",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "0701029001",
                "nik" => "19900201180215329",
                "nama" => "ARIE WIDYA MURNI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0712057801",
                "nik" => "19780512010419385",
                "nama" => "ARIS KUSWANTO",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "3",
            ],
            [
                "nidn" => "0022088801",
                "nik" => "19880822030815341",
                "nama" => "ATHIKA DWI WIJI UTAMI",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "0708108802",
                "nik" => "19881008030815336",
                "nama" => "ATIK WIDIYANTI",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "3",
            ],
            [
                "nidn" => "0726118301",
                "nik" => "19831126070317372",
                "nama" => "AWANG ANDHYKA",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0712018903",
                "nik" => "19890112170918380",
                "nama" => "AYU LUCY LARASSATY",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0706087001",
                "nik" => "19700806030815345",
                "nama" => "CHAIRIL ANWAR",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0713039305",
                "nik" => "19930313170222401",
                "nama" => "CYNTHIA EKA VIOLITA",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0715119701",
                "nik" => "19971115270921399",
                "nama" => "DEVIKA CHERLY PUTRIHADININGRUM",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0712088607",
                "nik" => "19860812070317377",
                "nama" => "DIAN FAHRIANI",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0701109601",
                "nik" => "19961001170222402",
                "nama" => "EDITA RACHMA KAMILA",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0725068502",
                "nik" => "19850625010915231",
                "nama" => "ELSA ROSYIDAH",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "3",
            ],
            [
                "nidn" => "0710038201",
                "nik" => "19820310170918383",
                "nama" => "ERLYNA TRI ROHMIATUN",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0722047703",
                "nik" => "19770422251014302",
                "nama" => "EVI MAHSUNAH",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0721049401",
                "nik" => "19940421270921396",
                "nama" => "FAJAR NUR YASIN",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0716078605",
                "nik" => "19860716011019388",
                "nama" => "FAKHRUR ROZY",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0707077501",
                "nik" => "19750707251014323",
                "nama" => "FERI KUSWANTO",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "3",
            ],
            [
                "nidn" => "0728049403",
                "nik" => "19940428051023423",
                "nama" => "GANAL ARIEF RAHMAWAN",
                "Penempatan" => "S1 - Pendidikan Islam Anak Usia Dini",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "12",
                "fakultas_id" => "5",
                "status" => "3",
            ],
            [
                "nidn" => "0729059501",
                "nik" => "19950529170222403",
                "nama" => "JEZIANO RIZKITA BOYAS",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "3",
            ],
            [
                "nidn" => "0701028302",
                "nik" => "19830201020919390",
                "nama" => "KAFIDIN MUZAKKI,SE.,M.AK",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "3",
            ],
            [
                "nidn" => "8915520021",
                "nik" => "19641124011114103",
                "nama" => "KHOIFULLOH",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0717078804",
                "nik" => "19880717251014305",
                "nama" => "LAILY MUZDALIFAH",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "2",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0730018505",
                "nik" => "19850130050115312",
                "nama" => "LAILY NOER HAMIDAH",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0705059801",
                "nik" => "19890505030815338",
                "nama" => "LISTIN FITRIANAH",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "1",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0710057807",
                "nik" => "19780510251014307",
                "nama" => "LUQMAN HAKIM",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "2",
            ],
            [
                "nidn" => "0728078502",
                "nik" => "19850728011114222",
                "nama" => "MACHFUDZIL ASROR",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0127118002",
                "nik" => "19801127030815348",
                "nama" => "MASYITAH NOVIYANTI",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0708058902",
                "nik" => "19890508050115311",
                "nama" => "MEDYA AYUNDA FITRI",
                "Penempatan" => "S1 - Teknik Kimia",
                "kode_jabfung" => "4",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "7",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0713068507",
                "nik" => "19850613030321329",
                "nama" => "MILLA AHMADIA APOLOGIA",
                "Penempatan" => "S1 - Pendidikan Islam Anak Usia Dini",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "12",
                "fakultas_id" => "5",
                "status" => "3",
            ],
            [
                "nidn" => "0729118805",
                "nik" => "19881129270921398",
                "nama" => "M. MUSTAQIM",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0709069405",
                "nik" => "19940609250822410",
                "nama" => "MOCHAMMAD MACHLUL ALAMIN",
                "Penempatan" => "S1 - Teknik Informatika",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "3",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0728059402",
                "nik" => "19940528170222408",
                "nama" => "MOHAMMAD SETYO WARDONO",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "0720048404",
                "nik" => "19840420010216354",
                "nama" => "MOHAMMAD TAUFIQ",
                "Penempatan" => "S1 - Akuntansi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "6",
                "fakultas_id" => "3",
                "status" => "4",
            ],
            [
                "nidn" => "0728108405",
                "nik" => "19841028250822411",
                "nama" => "MOH. ANANG ABIDIN",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "0725028403",
                "nik" => "19840225251014321",
                "nama" => "MUAWWINATUL LAILI",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "2",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0710058901",
                "nik" => "19890510050115313",
                "nama" => "MUCHAMMAD TAMYIZ",
                "Penempatan" => "S1 - Teknik Lingkungan",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "4",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0722117402",
                "nik" => "19741122161115353",
                "nama" => "MUHAFIDHAH NOVIE",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "3",
            ],
            [
                "nidn" => "0705069102",
                "nik" => "19910605170918384",
                "nama" => "MUHAMMAD ASSEGAF BAALWI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0713029101",
                "nik" => "19910213111217234",
                "nama" => "MUHAMMAD MANSUR YAFI",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "3",
            ],
            [
                "nidn" => "0714118407",
                "nik" => "19841114050115224",
                "nama" => "MUH. ARIS IZZUDIN",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "3",
            ],
            [
                "nidn" => "8971190024",
                "nik" => "",
                "nama" => "MUSTAIN",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0715029401",
                "nik" => "19940215170222404",
                "nama" => "NAFIA ILHAMA QURRATU\'AINI",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "3",
            ],
            [
                "nidn" => "0729067101",
                "nik" => "19710629170918381",
                "nama" => "NENY KURNIATI",
                "Penempatan" => "S1 - Teknik Informatika",
                "kode_jabfung" => "1",
                "kode_jabatan_dosen" => "2",
                "kode_fakultas" => "3",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "2101019302",
                "nik" => "19930101170222406",
                "nama" => "NOVARIA LAILATUL JANNAH",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "2128019602",
                "nik" => "19960128250822413",
                "nama" => "NUR NAFISATUL FITHRIYAH, M.PD",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "0728078801",
                "nik" => "19880728050115304",
                "nama" => "NURUL AINI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "1",
                "kode_fakultas" => "12",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0719108602",
                "nik" => "19861019030815342",
                "nama" => "PUTRA UJI DEVA SATRIO",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0721019301",
                "nik" => "19930121261022419",
                "nama" => "RIF\'ATUL ANITA",
                "Penempatan" => "S1 - Pendidikan Islam Anak Usia Dini",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "12",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "0706099101",
                "nik" => "19910906030117371",
                "nama" => "RIKKE KURNIAWATI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0716048405",
                "nik" => "19840416030815333",
                "nama" => "RINA SRI WULANDARI",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0713068802",
                "nik" => "19880613070317374",
                "nama" => "RIZKY ADITYA NUGROHO",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "2128119001",
                "nik" => "19901128261022416",
                "nama" => "ROFIQOH NIRWANA",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "0718038802",
                "nik" => "19880318270921395",
                "nama" => "RURI FADHILAH KURNIATI",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0711109502",
                "nik" => "19951011170222409",
                "nama" => "RYAN PURNOMO",
                "Penempatan" => "S1 - Pendidikan Bahasa Inggris",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "9",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0706109501",
                "nik" => "19951006261022418",
                "nama" => "SHOFIYATUZ ZAHROH",
                "Penempatan" => "S1 - Pendidikan Islam Anak Usia Dini",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "12",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "0713059002",
                "nik" => "19900513190815351",
                "nama" => "SONHAJI ARIF",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "1",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0716068805",
                "nik" => "19880616020516358",
                "nama" => "SYAHRI MU\'MIN",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0705118803",
                "nik" => "19881105080123417",
                "nama" => "SYAIFUDIN NOER",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0711037103",
                "nik" => "19710311251014319",
                "nama" => "TAQWANUR",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0730079002",
                "nik" => "19900730270921393",
                "nama" => "TRIAS WIDHA ANDARI",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "4",
            ],
            [
                "nidn" => "0722118801",
                "nik" => "19881122050115308",
                "nama" => "TRISNA KUMALA DHANISWARA",
                "Penempatan" => "S1 - Teknik Kimia",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "7",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0710057501",
                "nik" => "19750510030815334",
                "nama" => "UNTUNG USADA",
                "Penempatan" => "S1 - Teknik Industri",
                "kode_jabfung" => "3",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "5",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0723069102",
                "nik" => "19911115270921399",
                "nama" => "WAHYU EKO PUJIANTO",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "3",
            ],
            [
                "nidn" => "0729099001",
                "nik" => "19900929030815347",
                "nama" => "WAHYU MAULIDA LESTARI",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "4",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "0710078901",
                "nik" => "19890710180215331",
                "nama" => "YULIA TRI RAHKADIMA",
                "Penempatan" => "S1 - Teknik Kimia",
                "kode_jabfung" => "4",
                "kode_jabatan_dosen" => "3",
                "kode_fakultas" => "7",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "0724059204",
                "nik" => "19920524020919387",
                "nama" => "ZAHROTUL AZIZAH",
                "Penempatan" => "S1 - Teknik Kimia",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "2",
                "kode_fakultas" => "7",
                "fakultas_id" => "2",
                "status" => "4",
            ],
            [
                "nidn" => "",
                "nik" => "199403052508222414",
                "nama" => "Risalul Ummah, M.Pd.",
                "Penempatan" => "S1 - Pendidikan Guru Madrasah Ibtidaiyah",
                "kode_jabfung" => "2",
                "kode_jabatan_dosen" => "1",
                "kode_fakultas" => "11",
                "fakultas_id" => "5",
                "status" => "4",
            ],
            [
                "nidn" => "",
                "nik" => "19951105240523420",
                "nama" => "Ragil Noviyanti, M.I.Kom.",
                "Penempatan" => "S1 - Desain Komunikasi Visual",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "2",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "",
                "nik" => "19850812010415229",
                "nama" => "Ikhwan Abdillah, M.Pd.",
                "Penempatan" => "S1 - Sistem Informasi",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "0",
                "kode_fakultas" => "1",
                "fakultas_id" => "1",
                "status" => "3",
            ],
            [
                "nidn" => "",
                "nik" => "19931214020719238",
                "nama" => "Hikmah Luqiyah, M.Pd.",
                "Penempatan" => "S1 - Pendidikan Guru Sekolah Dasar",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "6",
                "kode_fakultas" => "10",
                "fakultas_id" => "4",
                "status" => "4",
            ],
            [
                "nidn" => "",
                "nik" => "19711108290124425",
                "nama" => "Dr. Syafiudin",
                "Penempatan" => "S1 - Manajemen",
                "kode_jabfung" => "0",
                "kode_jabatan_dosen" => "5",
                "kode_fakultas" => "8",
                "fakultas_id" => "3",
                "status" => "4",
            ],
        ];

        // $jsonArr = json_decode($rawJson);

        // for ($i = 0; $i < sizeof($jsonArr); $i++) {
        //     $success = SikBiodata::where('nik', stripNonNumeric($jsonArr[$i]['nik']))->update([
        //         'nidn' => stripNonNumeric($jsonArr[$i]['nidn']),
        //         'jabatan_fungsional_id' => stripNonNumeric($jsonArr[$i]['kode_jabfung']),
        //         'jabatan_strukdos_id' => stripNonNumeric($jsonArr[$i]['kode_jabatan_dosen']),
        //         'prodi_id' => stripNonNumeric($jsonArr[$i]['kode_fakultas'])
        //     ]);

        //     if ($success > 0) {
        //         echo $jsonArr[$i]['nama'] . " - Success";
        //     } else {
        //         echo $jsonArr[$i]['nama'] . " - Success";
        //     }
        // }

        for ($i = 0; $i < sizeof($jsonArr); $i++) {
            $target = SikBiodata::where('nik', stripNonNumeric($jsonArr[$i]['nik']))->first();

            $success = SikBiodata::where('nik', stripNonNumeric($jsonArr[$i]['nik']))->update([
                'nidn' => stripNonNumeric($jsonArr[$i]['nidn']),
                'jabatan_fungsional_id' => stripNonNumeric($jsonArr[$i]['kode_jabfung']),
                'jabatan_strukdos_id' => stripNonNumeric($jsonArr[$i]['kode_jabatan_dosen']),
                'prodi_id' => stripNonNumeric($jsonArr[$i]['kode_fakultas']),
                'fakultas_id' => stripNonNumeric($jsonArr[$i]['fakultas_id'])
            ]);

            if ($target) {
                if (($target->status == 1 || $target->status == 3) === false) {
                    $success = SikBiodata::where('nik', stripNonNumeric($jsonArr[$i]['nik']))->update([
                        'status' => stripNonNumeric($jsonArr[$i]['status']),
                    ]);

                    if ($success > 0) {
                        echo $jsonArr[$i]['nama'] . " - Success";
                    } else {
                        echo $jsonArr[$i]['nama'] . " - Failed";
                    }
                }
            } else {
                echo $jsonArr[$i]['nama'] . " - Not Found";
            }
            echo "\r\n";
        }
    }
}
